# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads/question_category/'),
        ),
    ]
