# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 13:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_questioncategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
