# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0003_auto_20171217_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='View360Question',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1024)),
                ('nb_views', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('last_edited_at', models.DateTimeField()),
                ('nb_answers', models.IntegerField()),
                ('tags', models.TextField()),
                ('category_name', models.TextField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'view_360_question',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
