# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qanda', '0004_auto_20171220_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='view360question',
            table='qanda_view360question',
        ),
    ]
