# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qanda', '0006_auto_20171231_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
