# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0010_auto_20180110_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='View360QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entrez une catégorie de question', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads/question_category/')),
                ('nb_questions', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'view_360_question_category',
                'managed': False,
            },
        ),
    ]
