# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0013_auto_20180207_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
