# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 13:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0014_profile_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='view360question',
            table='view_360_question',
        ),
    ]
