# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0016_auto_20180309_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/question_category/'),
        ),
    ]
